// NES Palette Shader
// =============================================================================
// Quantises every pixel to the closest colour in the NES master palette (54
// colours, NTSC canonical set from the color_tools library).
//
// The nearest-colour search is done entirely in linear RGB so the result
// matches what color_tools.distance.euclidean() would return.  For an even
// more perceptually accurate match swap the distance function below to the
// CIE76 / CIEDE2000 version (commented out at the bottom of this file).
//
// Uniforms
//   u_texture   – the source image / video frame (sampler2D)
//   u_pixelate  – optional pixelation factor (1 = off, 4 = 4×4 pixel blocks)
//   u_dither    – dither strength  0.0 = off, 1.0 = full Bayer 4×4
//
// How to copy this shader to another project:
//   1. Copy this file.
//   2. Bind u_texture to your source image/video.
//   3. (Optional) set u_pixelate and u_dither.
//   4. Render a fullscreen quad with quad.vert.
//
// Palette source: color_tools data/palettes/nes.json
// Generated by:   demos/palette_shader_demo.py
// =============================================================================

#version 330 core

in  vec2  v_texcoord;
out vec4  fragColor;

uniform sampler2D u_texture;
uniform float     u_pixelate; // default 4.0  (NES res ~256x224 → block=2–4)
uniform float     u_dither;   // default 0.0

// ---------------------------------------------------------------------------
// NES 54-colour palette (linear RGB, derived from color_tools nes.json)
// ---------------------------------------------------------------------------
const int NES_SIZE = 54;
const vec3 NES_PALETTE[54] = vec3[54](
    vec3(0.0000, 0.0000, 0.0000),  // nes_00 #000000
    vec3(0.4000, 0.4000, 0.4000),  // nes_01 #666666
    vec3(0.6824, 0.6824, 0.6824),  // nes_02 #aeaeae
    vec3(0.0000, 0.1647, 0.5333),  // nes_03 #002a88
    vec3(0.0824, 0.3725, 0.8549),  // nes_04 #155fda
    vec3(0.3922, 0.6902, 0.9961),  // nes_05 #64b0fe
    vec3(0.7569, 0.8784, 0.9961),  // nes_06 #c1e0fe
    vec3(0.0784, 0.0706, 0.6588),  // nes_07 #1412a8
    vec3(0.2588, 0.2510, 0.9961),  // nes_08 #4240fe
    vec3(0.5765, 0.5647, 0.9961),  // nes_09 #9390fe
    vec3(0.8314, 0.8275, 0.9961),  // nes_10 #d4d3fe
    vec3(0.2314, 0.0000, 0.6431),  // nes_11 #3b00a4
    vec3(0.4627, 0.1529, 1.0000),  // nes_12 #7627ff
    vec3(0.7804, 0.4667, 0.9961),  // nes_13 #c777fe
    vec3(0.9137, 0.7843, 0.9961),  // nes_14 #e9c8fe
    vec3(0.3608, 0.0000, 0.4941),  // nes_15 #5c007e
    vec3(0.6314, 0.1059, 0.8039),  // nes_16 #a11bcd
    vec3(0.9529, 0.4157, 0.9961),  // nes_17 #f36afe
    vec3(0.9843, 0.7647, 0.9961),  // nes_18 #fbc3fe
    vec3(0.4314, 0.0000, 0.2510),  // nes_19 #6e0040
    vec3(0.7216, 0.1176, 0.4863),  // nes_20 #b81e7c
    vec3(0.9961, 0.4314, 0.8039),  // nes_21 #fe6ecd
    vec3(0.9961, 0.7725, 0.9216),  // nes_22 #fec5eb
    vec3(0.4235, 0.0275, 0.0000),  // nes_23 #6c0700
    vec3(0.7098, 0.1961, 0.1255),  // nes_24 #b53220
    vec3(0.9961, 0.5098, 0.4392),  // nes_25 #fe8270
    vec3(0.9961, 0.8039, 0.7765),  // nes_26 #fecdc6
    vec3(0.3412, 0.1137, 0.0000),  // nes_27 #571d00
    vec3(0.6000, 0.3098, 0.0000),  // nes_28 #994f00
    vec3(0.9216, 0.6235, 0.1373),  // nes_29 #eb9f23
    vec3(0.9686, 0.8510, 0.6510),  // nes_30 #f7d9a6
    vec3(0.2039, 0.2078, 0.0000),  // nes_31 #343500
    vec3(0.4235, 0.4314, 0.0000),  // nes_32 #6c6e00
    vec3(0.7412, 0.7490, 0.0000),  // nes_33 #bdbf00
    vec3(0.8980, 0.9020, 0.5843),  // nes_34 #e5e695
    vec3(0.0471, 0.2863, 0.0000),  // nes_35 #0c4900
    vec3(0.2196, 0.5294, 0.0000),  // nes_36 #388700
    vec3(0.5373, 0.8510, 0.0000),  // nes_37 #89d900
    vec3(0.8157, 0.9412, 0.5922),  // nes_38 #d0f097
    vec3(0.0000, 0.3216, 0.0000),  // nes_39 #005200
    vec3(0.0510, 0.5804, 0.0000),  // nes_40 #0d9400
    vec3(0.3647, 0.8980, 0.1882),  // nes_41 #5de530
    vec3(0.7451, 0.9608, 0.6706),  // nes_42 #bef5ab
    vec3(0.0000, 0.3098, 0.0314),  // nes_43 #004f08
    vec3(0.0000, 0.5647, 0.1961),  // nes_44 #009032
    vec3(0.2706, 0.8824, 0.5098),  // nes_45 #45e182
    vec3(0.7059, 0.9529, 0.8039),  // nes_46 #b4f3cd
    vec3(0.0000, 0.2510, 0.3059),  // nes_47 #00404e
    vec3(0.0000, 0.4863, 0.5569),  // nes_48 #007c8e
    vec3(0.2824, 0.8078, 0.8745),  // nes_49 #48cedf
    vec3(0.7098, 0.9255, 0.9529),  // nes_50 #b5ecf3
    vec3(0.3098, 0.3098, 0.3098),  // nes_51 #4f4f4f
    vec3(0.7216, 0.7216, 0.7216),  // nes_52 #b8b8b8
    vec3(0.9961, 0.9961, 0.9961)   // nes_53 #fefefe
);

// ---------------------------------------------------------------------------
// Bayer 4×4 ordered dither matrix (normalised to [-0.5, 0.5])
// ---------------------------------------------------------------------------
float bayer4x4(ivec2 p) {
    int x = p.x & 3;
    int y = p.y & 3;
    // Standard Bayer 4×4 thresholds (0–15), normalised to [-0.5, 0.5]
    int idx = (y * 4 + x);
    float[16] M = float[16](
         0.0,  8.0,  2.0, 10.0,
        12.0,  4.0, 14.0,  6.0,
         3.0, 11.0,  1.0,  9.0,
        15.0,  7.0, 13.0,  5.0
    );
    return (M[idx] / 16.0) - 0.5;   // range [-0.5, 0.5]
}

// ---------------------------------------------------------------------------
// Nearest-colour search in linear RGB space
// (identical to color_tools.distance.euclidean)
// ---------------------------------------------------------------------------
vec3 nearest_nes(vec3 color) {
    float best_dist = 1e9;
    vec3  best_col  = NES_PALETTE[0];
    for (int i = 0; i < NES_SIZE; i++) {
        vec3  delta = color - NES_PALETTE[i];
        float dist  = dot(delta, delta);   // squared Euclidean – no need for sqrt
        if (dist < best_dist) {
            best_dist = dist;
            best_col  = NES_PALETTE[i];
        }
    }
    return best_col;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------
void main() {
    // Optional pixel-block quantisation (emulates low resolution)
    vec2 uv = v_texcoord;
    if (u_pixelate > 1.0) {
        vec2 texSize  = vec2(textureSize(u_texture, 0));
        vec2 blockSize = vec2(u_pixelate) / texSize;
        uv = (floor(uv / blockSize) + 0.5) * blockSize;
    }

    vec3 color = texture(u_texture, uv).rgb;

    // Optional Bayer dither (perturbs the colour before quantisation)
    if (u_dither > 0.0) {
        ivec2 px = ivec2(gl_FragCoord.xy);
        float noise = bayer4x4(px) * u_dither * (1.0 / float(NES_SIZE));
        color = clamp(color + vec3(noise), 0.0, 1.0);
    }

    fragColor = vec4(nearest_nes(color), 1.0);
}

// ---------------------------------------------------------------------------
// Alternative: perceptual match in CIE LAB space (CIE76 delta-E)
// Uncomment to swap the Euclidean RGB distance for a LAB-based one.
// Requires passing the palette as LAB values (not done here by default).
// ---------------------------------------------------------------------------
// vec3 rgb2lab_approx(vec3 c) { ... }
// float delta_e76(vec3 a, vec3 b) { vec3 d = a - b; return sqrt(dot(d,d)); }
