// Palette LUT Shader
// =============================================================================
// Universal palette quantisation shader driven by a 1-D palette LUT texture.
//
// Instead of a hard-coded colour array, the palette is supplied as a 1×N PNG
// strip (one pixel per palette colour, generated by generate_palette_textures.py).
// This means any palette can be used without recompiling the shader — just swap
// the texture and update u_palette_size.
//
// Uniforms
//   u_texture      – source image / video frame (sampler2D, unit 0)
//   u_palette      – palette LUT texture: 1×N strip, RGB, NEAREST filter (unit 1)
//   u_palette_size – number of colours in the palette (int)
//   u_pixelate     – pixel-block size; 1.0 = off, 4.0 = 4×4 blocks
//   u_dither       – Bayer 4×4 dither strength: 0.0 = off, 1.0 = full
//
// LUT texture format
//   Width  = number of palette colours (N)
//   Height = 1
//   Each texel is the RGB value of palette entry i.
//   Sample with: texture(u_palette, vec2((i + 0.5) / N, 0.5)).rgb
//
// Usage in palette_lut_demo.py
//   1. Generate palette textures:   python generate_palette_textures.py
//   2. Run the demo:                python palette_lut_demo.py image.png --lut palette_textures/nes.png
//   3. Switch at runtime:           press L to browse LUTs in the palette_textures/ folder
//
// Palette source: any color_tools palette PNG (see generate_palette_textures.py)
// =============================================================================

#version 330 core

in  vec2  v_texcoord;
out vec4  fragColor;

uniform sampler2D u_texture;       // source image/video  (unit 0)
uniform sampler2D u_palette;       // palette LUT strip    (unit 1)
uniform int       u_palette_size;  // number of colours in LUT
uniform float     u_pixelate;      // pixel-block size (1.0 = off)
uniform float     u_dither;        // Bayer dither strength (0.0 = off)

// ---------------------------------------------------------------------------
// Bayer 4×4 ordered dither matrix (normalised to [-0.5, 0.5])
// ---------------------------------------------------------------------------
float bayer4x4(ivec2 p) {
    int x = p.x & 3;
    int y = p.y & 3;
    int idx = y * 4 + x;
    float[16] M = float[16](
         0.0,  8.0,  2.0, 10.0,
        12.0,  4.0, 14.0,  6.0,
         3.0, 11.0,  1.0,  9.0,
        15.0,  7.0, 13.0,  5.0
    );
    return (M[idx] / 16.0) - 0.5;   // range [-0.5, 0.5]
}

// ---------------------------------------------------------------------------
// Nearest-colour search via LUT texture sample
// ---------------------------------------------------------------------------
vec3 nearest_lut(vec3 color) {
    float best_dist = 1e9;
    vec3  best_col  = texture(u_palette, vec2(0.5 / float(u_palette_size), 0.5)).rgb;

    for (int i = 0; i < u_palette_size; i++) {
        float u   = (float(i) + 0.5) / float(u_palette_size);
        vec3  pal = texture(u_palette, vec2(u, 0.5)).rgb;
        vec3  d   = color - pal;
        float dist = dot(d, d);   // squared Euclidean – no sqrt needed
        if (dist < best_dist) {
            best_dist = dist;
            best_col  = pal;
        }
    }
    return best_col;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------
void main() {
    // Optional pixel-block quantisation (emulates low resolution)
    vec2 uv = v_texcoord;
    if (u_pixelate > 1.0) {
        vec2 texSize   = vec2(textureSize(u_texture, 0));
        vec2 blockSize = vec2(u_pixelate) / texSize;
        uv = (floor(uv / blockSize) + 0.5) * blockSize;
    }

    vec3 color = texture(u_texture, uv).rgb;

    // Optional Bayer dither (perturbs colour before quantisation)
    if (u_dither > 0.0) {
        ivec2 px    = ivec2(gl_FragCoord.xy);
        float noise = bayer4x4(px) * u_dither * (1.0 / float(u_palette_size));
        color = clamp(color + vec3(noise), 0.0, 1.0);
    }

    fragColor = vec4(nearest_lut(color), 1.0);
}
