#!/usr/bin/env python3
"""
Palette LUT Shader Demo
=======================
Real-time palette conversion demo using pygame + moderngl with a universal
LUT-driven shader.  Unlike palette_shader_demo.py, a single shader is used
for all palettes — the palette colours are supplied as a 1-D PNG strip texture
(generated by generate_palette_textures.py) rather than being hard-coded in GLSL.

Supported input
---------------
  Any image or video file.  Pass any palette PNG with --lut.

Usage
-----
  python palette_lut_demo.py image.png --lut palette_textures/nes.png
  python palette_lut_demo.py video.mp4 --lut palette_textures/gameboy.png --pixelate 4
  python palette_lut_demo.py image.jpg --lut palette_textures/cga16.png --dither 0.8

  # Generate palette textures first if not already done:
  python generate_palette_textures.py

Keyboard shortcuts
------------------
  [  /  ]   Previous / next LUT in palette_textures/ folder
  +  /  -   Increase / decrease pixel-block size
  D         Toggle dither on/off
  R         Reload shader from disk (hot-reload)
  S         Save screenshot
  Space     Pause / resume video
  Q / Esc   Quit
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Optional

# Third-party imports
try:
    import pygame
except ImportError:
    print("pygame is required.  Run:  pip install -r requirements.txt")
    sys.exit(1)

try:
    import moderngl
except ImportError:
    print("moderngl is required.  Run:  pip install -r requirements.txt")
    sys.exit(1)

try:
    import numpy as np
except ImportError:
    print("numpy is required.  Run:  pip install -r requirements.txt")
    sys.exit(1)

try:
    from PIL import Image
except ImportError:
    print("Pillow is required.  Run:  pip install -r requirements.txt")
    sys.exit(1)

# Optional: opencv for video
try:
    import cv2
    HAS_CV2 = True
except ImportError:
    HAS_CV2 = False

import time

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
DEMO_DIR        = Path(__file__).parent
SHADER_DIR      = DEMO_DIR / "shaders"
PALETTE_TEX_DIR = DEMO_DIR / "palette_textures"

DEFAULT_PIXELATE = 4.0


# ---------------------------------------------------------------------------
# Shader helpers
# ---------------------------------------------------------------------------

def _read_shader(path: Path) -> str:
    with open(path, "r", encoding="utf-8") as f:
        return f.read()


def build_program(ctx: moderngl.Context) -> moderngl.Program:
    vert_src = _read_shader(SHADER_DIR / "quad.vert")
    frag_src = _read_shader(SHADER_DIR / "palette_lut.frag")
    return ctx.program(vertex_shader=vert_src, fragment_shader=frag_src)


# ---------------------------------------------------------------------------
# Texture helpers
# ---------------------------------------------------------------------------

def make_image_texture(ctx: moderngl.Context, rgb_array: np.ndarray) -> moderngl.Texture:
    """Upload an RGB image array as a moderngl texture (unit 0)."""
    h, w = rgb_array.shape[:2]
    flipped = np.ascontiguousarray(np.flipud(rgb_array))
    tex = ctx.texture((w, h), 3, flipped.tobytes())
    tex.filter = (moderngl.LINEAR, moderngl.LINEAR)
    tex.repeat_x = False
    tex.repeat_y = False
    return tex


def make_lut_texture(ctx: moderngl.Context, lut_path: Path) -> tuple[moderngl.Texture, int]:
    """
    Load a 1×N palette PNG strip and upload it as a LUT texture (unit 1).

    Returns:
        (texture, palette_size)
    """
    img = Image.open(lut_path).convert("RGB")
    arr = np.array(img, dtype=np.uint8)  # shape (1, N, 3) or (H, N, 3)
    # Use only the first row — height > 1 is just for preview
    row = arr[0]  # (N, 3)
    n   = row.shape[0]
    tex = ctx.texture((n, 1), 3, row.tobytes())
    tex.filter  = (moderngl.NEAREST, moderngl.NEAREST)
    tex.repeat_x = False
    tex.repeat_y = False
    return tex, n


def load_image(path: Path) -> np.ndarray:
    img = Image.open(path).convert("RGB")
    return np.array(img, dtype=np.uint8)


# ---------------------------------------------------------------------------
# Fullscreen-quad VAO
# ---------------------------------------------------------------------------

def make_quad_vao(ctx: moderngl.Context, program: moderngl.Program) -> moderngl.VertexArray:
    vertices = np.array([
        -1.0, -1.0,  0.0,  0.0,
         1.0, -1.0,  1.0,  0.0,
         1.0,  1.0,  1.0,  1.0,
        -1.0, -1.0,  0.0,  0.0,
         1.0,  1.0,  1.0,  1.0,
        -1.0,  1.0,  0.0,  1.0,
    ], dtype=np.float32)
    vbo = ctx.buffer(vertices.tobytes())
    return ctx.vertex_array(program, [(vbo, "2f 2f", "in_position", "in_texcoord")])


# ---------------------------------------------------------------------------
# LUT browser — sorted list of PNGs in palette_textures/
# ---------------------------------------------------------------------------

def find_luts(directory: Path) -> list[Path]:
    """Return sorted list of .png files in the given directory."""
    return sorted(directory.glob("*.png"))


# ---------------------------------------------------------------------------
# Video reader
# ---------------------------------------------------------------------------

class VideoReader:
    def __init__(self, path: Path) -> None:
        if not HAS_CV2:
            raise RuntimeError(
                "opencv-python is required for video support.\n"
                "Run:  pip install -r requirements.txt"
            )
        self.cap = cv2.VideoCapture(str(path))
        if not self.cap.isOpened():
            raise FileNotFoundError(f"Cannot open video: {path}")
        self.fps = self.cap.get(cv2.CAP_PROP_FPS) or 30.0
        self._paused = False
        self._last_frame: Optional[np.ndarray] = None
        self._next_frame_time = time.monotonic()

    def next_frame(self) -> Optional[np.ndarray]:
        now = time.monotonic()
        if self._paused:
            return self._last_frame
        if now < self._next_frame_time:
            return self._last_frame
        ret, bgr = self.cap.read()
        if not ret:
            self.cap.set(cv2.CAP_PROP_POS_FRAMES, 0)
            ret, bgr = self.cap.read()
            if not ret:
                return self._last_frame
        rgb = cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB)
        self._last_frame = rgb
        self._next_frame_time = now + 1.0 / self.fps
        return rgb

    def toggle_pause(self) -> None:
        self._paused = not self._paused

    @property
    def paused(self) -> bool:
        return self._paused

    def release(self) -> None:
        self.cap.release()


# ---------------------------------------------------------------------------
# Main application
# ---------------------------------------------------------------------------

def run(
    source_path: Path,
    lut_path: Path,
    pixelate: float,
    dither: float,
    window_scale: float,
) -> None:
    is_video = source_path.suffix.lower() in {
        ".mp4", ".avi", ".mov", ".mkv", ".webm", ".flv", ".wmv",
    }

    video: Optional[VideoReader] = None
    frame: Optional[np.ndarray] = None

    if is_video:
        print(f"Loading video: {source_path}")
        video = VideoReader(source_path)
        frame = video.next_frame()
        if frame is None:
            print("Error: could not read first frame from video.")
            sys.exit(1)
        src_h, src_w = frame.shape[:2]
    else:
        print(f"Loading image: {source_path}")
        frame = load_image(source_path)
        src_h, src_w = frame.shape[:2]

    # Window dimensions
    win_w = int(src_w * window_scale)
    win_h = int(src_h * window_scale)
    max_dim = 1024
    if win_w > max_dim or win_h > max_dim:
        scale = max_dim / max(win_w, win_h)
        win_w = int(win_w * scale)
        win_h = int(win_h * scale)

    # pygame + moderngl setup
    pygame.init()

    pygame.display.gl_set_attribute(pygame.GL_CONTEXT_MAJOR_VERSION, 3)
    pygame.display.gl_set_attribute(pygame.GL_CONTEXT_MINOR_VERSION, 3)
    pygame.display.gl_set_attribute(
        pygame.GL_CONTEXT_PROFILE_MASK, pygame.GL_CONTEXT_PROFILE_CORE
    )
    pygame.display.gl_set_attribute(pygame.GL_CONTEXT_FORWARD_COMPATIBLE_FLAG, 1)

    screen = pygame.display.set_mode((win_w, win_h), pygame.OPENGL | pygame.DOUBLEBUF)
    clock  = pygame.time.Clock()

    ctx = moderngl.create_context()

    # Shader + geometry (single program for all palettes)
    program = build_program(ctx)
    vao     = make_quad_vao(ctx, program)

    # Source image texture on unit 0
    img_texture = make_image_texture(ctx, frame)
    img_texture.use(0)
    if "u_texture" in program:
        program["u_texture"].value = 0  # type: ignore[union-attr]

    # LUT browser state
    lut_list    = find_luts(lut_path.parent if lut_path.is_file() else PALETTE_TEX_DIR)
    if not lut_list:
        print(f"No palette PNG files found in {PALETTE_TEX_DIR}")
        sys.exit(1)

    # Find starting index
    try:
        lut_index = lut_list.index(lut_path.resolve())
    except ValueError:
        lut_index = 0

    current_lut_path  = lut_list[lut_index]
    lut_texture, palette_size = make_lut_texture(ctx, current_lut_path)
    lut_texture.use(1)
    if "u_palette" in program:
        program["u_palette"].value = 1  # type: ignore[union-attr]
    if "u_palette_size" in program:
        program["u_palette_size"].value = palette_size  # type: ignore[union-attr]

    pixelate_val = pixelate if pixelate > 0 else DEFAULT_PIXELATE
    dither_val   = dither

    def set_uniforms() -> None:
        if "u_pixelate" in program:
            program["u_pixelate"].value = pixelate_val  # type: ignore[union-attr]
        if "u_dither" in program:
            program["u_dither"].value = dither_val  # type: ignore[union-attr]

    set_uniforms()

    def update_title() -> None:
        lut_name = current_lut_path.stem
        pix_str  = f"pixelate={pixelate_val:.0f}"
        dth_str  = f"dither={dither_val:.1f}"
        n_str    = f"n={palette_size}"
        paused   = "  [PAUSED]" if (video and video.paused) else ""
        pygame.display.set_caption(
            f"Palette LUT Demo – {lut_name}  {n_str}  {pix_str}  {dth_str}{paused}"
        )

    def load_lut(index: int) -> None:
        nonlocal lut_index, current_lut_path, lut_texture, palette_size
        lut_index        = index % len(lut_list)
        current_lut_path = lut_list[lut_index]
        lut_texture.release()
        lut_texture, palette_size = make_lut_texture(ctx, current_lut_path)
        lut_texture.use(1)
        if "u_palette" in program:
            program["u_palette"].value = 1  # type: ignore[union-attr]
        if "u_palette_size" in program:
            program["u_palette_size"].value = palette_size  # type: ignore[union-attr]
        img_texture.use(0)  # keep source on unit 0
        set_uniforms()
        update_title()
        print(f"LUT: {current_lut_path.name}  ({palette_size} colours)")

    def reload_shader() -> None:
        nonlocal program, vao
        try:
            program.release()
            vao.release()
            program = build_program(ctx)
            vao     = make_quad_vao(ctx, program)
            img_texture.use(0)
            if "u_texture" in program:
                program["u_texture"].value = 0  # type: ignore[union-attr]
            lut_texture.use(1)
            if "u_palette" in program:
                program["u_palette"].value = 1  # type: ignore[union-attr]
            if "u_palette_size" in program:
                program["u_palette_size"].value = palette_size  # type: ignore[union-attr]
            set_uniforms()
            print("Shader reloaded.")
        except Exception as exc:
            print(f"Shader reload failed: {exc}")

    update_title()
    print(f"\nLUT: {current_lut_path.name}  ({palette_size} colours)")
    print("\nKeyboard shortcuts:")
    print("  [ / ]   Previous / next palette LUT")
    print("  + / -   Increase / decrease pixel-block size")
    print("  D       Toggle dither")
    print("  R       Reload shader from disk")
    print("  S       Save screenshot")
    print("  Space   Pause/resume video")
    print("  Q/Esc   Quit\n")

    running          = True
    screenshot_count = 0

    while running:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False

            elif event.type == pygame.KEYDOWN:
                key = event.key

                if key in (pygame.K_q, pygame.K_ESCAPE):
                    running = False

                # Browse LUTs
                elif key == pygame.K_RIGHTBRACKET:
                    load_lut(lut_index + 1)
                elif key == pygame.K_LEFTBRACKET:
                    load_lut(lut_index - 1)

                # Pixel-block size
                elif key in (pygame.K_PLUS, pygame.K_EQUALS, pygame.K_KP_PLUS):
                    pixelate_val = min(pixelate_val + 1.0, 32.0)
                    set_uniforms()
                    update_title()
                elif key in (pygame.K_MINUS, pygame.K_KP_MINUS):
                    pixelate_val = max(pixelate_val - 1.0, 1.0)
                    set_uniforms()
                    update_title()

                # Dither toggle
                elif key == pygame.K_d:
                    dither_val = 0.0 if dither_val > 0 else 1.0
                    set_uniforms()
                    update_title()

                # Reload shader
                elif key == pygame.K_r:
                    reload_shader()

                # Screenshot
                elif key == pygame.K_s:
                    screenshot_count += 1
                    fname = DEMO_DIR / f"screenshot_{current_lut_path.stem}_{screenshot_count:03d}.png"
                    raw = ctx.screen.read(components=3)
                    img = Image.frombytes("RGB", (win_w, win_h), raw)
                    img = img.transpose(Image.Transpose.FLIP_TOP_BOTTOM)
                    img.save(fname)
                    print(f"Screenshot saved: {fname}")

                # Pause/resume
                elif key == pygame.K_SPACE:
                    if video:
                        video.toggle_pause()
                        update_title()

        # Video frame update
        if video:
            new_frame = video.next_frame()
            if new_frame is not None and not video.paused:
                frame = new_frame
                flipped = np.ascontiguousarray(np.flipud(frame))
                img_texture.write(flipped.tobytes())

        # Render
        ctx.viewport = (0, 0, win_w, win_h)
        ctx.clear(0.0, 0.0, 0.0)
        vao.render(moderngl.TRIANGLES)
        pygame.display.flip()

        clock.tick(60)

    # Cleanup
    if video:
        video.release()
    lut_texture.release()
    img_texture.release()
    vao.release()
    program.release()
    pygame.quit()


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Retro palette LUT shader demo (pygame + moderngl)",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "source",
        type=Path,
        help="Image or video file to display",
    )
    parser.add_argument(
        "--lut",
        type=Path,
        default=PALETTE_TEX_DIR / "nes.png",
        metavar="PNG",
        help=(
            "Palette LUT PNG strip (default: palette_textures/nes.png). "
            "Use [ / ] at runtime to browse all PNGs in the same folder."
        ),
    )
    parser.add_argument(
        "--pixelate",
        type=float,
        default=0.0,
        help="Pixel-block size (0 = use default 4.0, 1 = off)",
    )
    parser.add_argument(
        "--dither",
        type=float,
        default=0.0,
        help="Bayer dither strength: 0.0 (off) to 1.0 (full)",
    )
    parser.add_argument(
        "--scale",
        type=float,
        default=1.0,
        help="Window scale factor (default: 1.0)",
    )

    args = parser.parse_args()

    if not args.source.exists():
        print(f"Error: file not found: {args.source}")
        sys.exit(1)

    if not args.lut.exists():
        print(f"Error: LUT file not found: {args.lut}")
        print("Generate palette textures first:  python generate_palette_textures.py")
        sys.exit(1)

    run(
        source_path=args.source,
        lut_path=args.lut.resolve(),
        pixelate=args.pixelate,
        dither=args.dither,
        window_scale=args.scale,
    )


if __name__ == "__main__":
    main()
